Croatian translation 20220827
kimai/www.kimai.org pull request #144
Opened 2022-08-27 18:38 UTC by milotype

Update files with Croatian translation

2022-08-27 21:34 UTC, kevinpapst requested changes
Awesome work, thanks 👍 

There is just one minor issue and then I can merge.

2022-08-28 09:11 UTC, milotype commented on _data/menu.yml
> +  - dokumenti
OK, I just reverted translated identifiers back into english

2022-08-28 22:20 UTC, kevinpapst approved these changes
Thank you so much 👍 looks good, I am going to merge now and then we can do a live chec 😄

2022-08-28 22:20 UTC, merged

2022-08-29 13:28 UTC, milotype commented
@kevinpapst Thanks, most of it looks good.

One thing I don't understand is the file **_features/hr/multi-language.md**. I've translated the languages (see https://github.com/kimai/www.kimai.org/pull/144/commits/0d4703f7167c3cfdb3cd5e358fbbd790c5094939), but now they are displayed in english in the featue **Multilingual** at https://www.kimai.org/hr/!?

Can you correct that, or should I make a new PR?

2022-08-29 14:10 UTC, kevinpapst commented
I changed that before merging. 

This list is universal across all languages, because I know myself: if I add a language to the list, I forget to add it to all translations ;-)

And one more thought from my side: translating language names isn't really worth the trouble. If you are looking for your own language in a translated page, do you find it more easily to detect it in English or translated in the page language?

Conclusion: let's leave it as is :)