Update Croatian translations in "data" folder
kimai/www.kimai.org pull request #148
Opened 2022-09-02 23:27 UTC by milotype

2022-09-03 10:30 UTC, kevinpapst requested changes
Looks good, thanks 👍 

Just one issue:
can you please revert the `url` changes in `_data/trans-menu.yml`. Changing `name` works(!), but the URL should stay the same. Mainly because it is already "out there" and you should not change URLs that Google already knows.

2022-09-03 16:31 UTC, milotype commented
Yes, I can change it ... but IMO URL's like `https://www.kimai.org/hr/download.html` (translated into `url: /hr/preuzimanje.html`) and slugs like `https://www.kimai.org/hr/store/` (translated into `https://www.kimai.org/hr/trgovina/` may, and IMO and as far as I know, they can/should be tanslated. Google will learn it ...

Nevertheless, decide what you want, and I will make the changes ... and will follow it for other translations.

2022-09-03 21:20 UTC, kevinpapst commented
The website is run by Jekyll, which has terrible/bad support for redirects. And changing the URL has very limited SEO impact. So yes please, change the URLs.

2022-09-04 12:38 UTC, kevinpapst requested changes
thanks for reverting, but the new URLs are still not the old ones ;-)

2022-09-04 12:38 UTC, kevinpapst commented on _data/trans-menu.yml
> +    url: /hr/donate/
```suggestion
    url: /hr/donacije.html
```

2022-09-04 12:38 UTC, kevinpapst commented on _data/trans-menu.yml
> +    url: /hr/about/
```suggestion
    url: /hr/o-programu-kimai.html
```

2022-09-04 12:38 UTC, kevinpapst commented on _data/trans-menu.yml
> +    url: /hr/demo/
```suggestion
    url: /hr/demo.html
```

2022-09-04 13:24 UTC, milotype commented
OK, I've commited your changes.
But I still don't understand when to use just an URL slug and when to use an URL with a `.html` extension.
I'm really sorry, but as I'm not a programmer and I sometimes do not understand such issues ... :-(

2022-09-04 13:32 UTC, kevinpapst commented
Nothing to be sorry about, that is why there are "code reviews". I know Git is much more complicated than using weblate and I really appreciate your support here!!!!

Think of URLs as your computers hard drive. Using `.html` or a slug means it is a file, using a `/` means it is a directory where a search engine will find more files (e.g. the marketplace and all plugins inside).

There is no real difference between adding and removing the .html, but there are technical reasons to better use .html.
And having a directory means that a file called `index.html` is served. Technical nonsense that I do not want to explain in detail here 😁 And at some points I made a mistake in the past, but I do not want to correct that, because changing URLs can lead to some serious consequences in Google.

2022-09-04 13:32 UTC, kevinpapst approved these changes
Thank you @milotype 👍

2022-09-04 13:32 UTC, merged