Added Helsinki-Systems Lexoffice plugin to the store
kimai/www.kimai.org pull request #296
Opened 2023-08-26 14:08 UTC by MariusGoehring

2023-08-27 16:01 UTC, kevinpapst requested changes

2023-08-27 16:01 UTC, kevinpapst commented on _includes/store/helsinkisystems-lexoffice.md
> +{% include store/helsinkisystems-lexoffice.md %}
This file must contain the entire product description.

Right now it references itself.

2023-08-31 08:46 UTC, kevinpapst requested changes
did you try these changes in jekyll?

2023-08-31 08:46 UTC, kevinpapst commented on _data/de/store.yml
> +    helsinkisystems-ledxoffice:
```suggestion
    helsinkisystems-lexoffice:
```

2023-08-31 08:46 UTC, kevinpapst commented on _data/store/helsinkisystems-lexoffice.yaml
> +        - [ "2.0" ]
[ "plugin version", "min kimai version" ]

2023-08-31 08:46 UTC, kevinpapst commented on _includes/store/helsinkisystems-lexoffice.md
> +For lading the plugin, all you need to do after unzipping the plugin in the /var/plugins/ directory of your kimai installation, is to relaod the cache:
```suggestion
For loading the plugin, all you need to do after unzipping the plugin in the /var/plugins/ directory of your Kimai installation, is to reload the cache:
```

2023-08-31 10:50 UTC, kevinpapst requested changes
Again: did you try this in jekyll locally?

2023-08-31 10:50 UTC, kevinpapst commented on _includes/store/helsinkisystems-lexoffice.md
> +``` composer require helsinki-systems/lexoffice-php-sdk:dev-master ```
Using composer will break the next update of Kimai.
People will pull and don't understand why the update doesn't work. 

You need to add a clear sentence about this expected problem and then link to https://www.kimai.org/documentation/updates.html#changed-files

2023-08-31 10:50 UTC, kevinpapst commented on _includes/store/helsinkisystems-lexoffice.md
> +For loading the plugin, all you need to do after unzipping the plugin in the /var/plugins/ directory of your Kimai installation, is to reload the cache:
Installation instructions are auto-generated. 
Please remove that last sentence.

2023-08-31 10:50 UTC, kevinpapst commented on _data/store/helsinkisystems-lexoffice.yaml
> +gumroad: Lexoffice
Can people buy at Gumroad and Lemonsqueezy?

2023-08-31 10:51 UTC, kevinpapst commented on _data/store/helsinkisystems-lexoffice.yaml
> +documentation: plugin-lexoffice
this creates a link to a none existing documentation page

2023-08-31 11:01 UTC, MariusGoehring commented
> Again: did you try this in jekyll locally?
yes, i tested it locally.

2023-11-10 10:30 UTC, Scriptkiddi commented on _includes/store/helsinkisystems-lexoffice.md
> +People will pull and don't understand why the update doesn't work.
this sentence does not belong here @MariusGoehring please fix

2023-11-10 10:34 UTC, Scriptkiddi commented on _includes/store/helsinkisystems-lexoffice.md
> +People will pull and don't understand why the update doesn't work.
On second though please change the paragraph to something like:
```
UPDATE WARNING: As this plugin uses composer it breaks on Kimai Updates.
You will have to rerun the composer installation step after each update. 
See https://www.kimai.org/documentation/updates.html#changed-files for more information
```

2023-11-11 16:55 UTC, MariusGoehring commented
Rebased and tested on jekyll

2023-11-11 20:23 UTC, kevinpapst requested changes

2023-11-11 20:23 UTC, kevinpapst commented on _data/en/store.yml
> +        title: Lexoffice (automatically create invoices in Lexoffice from invoices in Kimai)
The title is something like "Lexoffice Invoice" or Lexoffice Invoice Sync" right?
The intro contains the description. 
Please remove the (rest) from the title and while you are on it: remove it from Budget watcher as well please in german and english.

2023-11-11 20:23 UTC, kevinpapst commented on _data/store/helsinkisystems-lexoffice.yaml
> +    name: "Lexoffice"
The namespace Lexoffice is pretty generic. If it is only about Invoices, then please rename it to LexofficeInvoice

2023-11-11 20:23 UTC, kevinpapst commented on _includes/store/helsinkisystems-lexoffice.md
> +You will have to rerun the composer installation step after each update.
I think this is still not clear / I doubt that regular users will understand that. 
Maybe you can create `include/composer-update-warning.md` and add something like:

UPDATE WARNING: The next time you update Kimai you will see something like ... (show the merge message that will likely appear) what happens and you have to revert your changes first, then update Kimai and afterwards reinstall the plugin. Please read https://www.kimai.org/documentation/updates.html#changed-files

Then I can re-use this include on the LDAP docu page as well and we can update the shown warning on all related pages.

2023-11-11 20:23 UTC, kevinpapst commented on _store/helsinkisystems-lexoffice.md
> +title: Lexoffice plugin (automatically create invoices in Lexoffice from Kimai invoices)
```suggestion
title: Lexoffice Invoice Sync
```

or whatever you choose as title above

2023-11-12 16:43 UTC, MariusGoehring commented
Okay have added the composer-update-warning.md. Also included it in _includes/store/helsinkisystems-lexoffice.md to be sure it is likned in there. If you have plans to automatically include it, tell me and i will remove the include from there

2023-11-12 22:20 UTC, kevinpapst approved these changes
Thanks 👍  I'll merge and make some smaller adjustments myself

2023-11-12 22:20 UTC, merged