RecurringBudgetBundle -> Update for Kimai 2
kimai/www.kimai.org pull request #494
Opened 2024-10-24 11:56 UTC by peat85

The plugin has been updated for use in Kimai 2 (`^2.20.0`).

2024-10-29 20:56 UTC, kevinpapst commented on _includes/store/pcsg-recurring-budget-bundle.md
> +# Now ready for Kimai 2!
Mentions of versions always confuse users. I have a sad history of that. I will remove it.
```suggestion
```

2024-10-29 20:57 UTC, kevinpapst commented on _data/store/pcsg-recurring-budget-bundle.yml
> +shop: "https://en.shop.pcsg.de/Plugins/Kimai/Recurring-Budget"
Do you have an affiliate program?

2024-11-13 14:14 UTC, peat85 commented on _data/store/pcsg-recurring-budget-bundle.yml
> +shop: "https://en.shop.pcsg.de/Plugins/Kimai/Recurring-Budget"
> Do you have an affiliate program?

Not at the moment.

2025-03-13 17:32 UTC, kevinpapst requested changes

2025-03-13 17:32 UTC, kevinpapst commented on _includes/store/pcsg-recurring-budget-bundle.md
> +A Kimai plugin that automatically adds a recurring money or time budget to your projects with a custom interval. Set
```suggestion
Automatically add a recurring money or time budget to your projects with a custom interval. Set
```

2025-03-13 17:32 UTC, kevinpapst commented on _includes/store/pcsg-recurring-budget-bundle.md
> +  * Recalculate budget intervals via frontend: The budgets history view now offers the option to recalculate a budget interval directly
```suggestion
* Automatic budget expiration: You can now configure your projects to expire unused budget after a set amount of intervals
* Recalculate budget intervals via frontend: The budgets history view now offers the option to recalculate a budget interval directly
```

2025-03-13 17:32 UTC, kevinpapst commented on _includes/store/pcsg-recurring-budget-bundle.md
> +* Kimai, **v2.20.0** or higher
```suggestion
* Kimai 2.20.0 or higher
```

2025-03-13 17:34 UTC, kevinpapst approved these changes

2025-03-13 17:34 UTC, merged