added hmr-it-controlling-bundle
kimai/www.kimai.org pull request #76
Opened 2020-09-17 08:02 UTC by hmr-it-jr

Added a new bundle which I've developed.

A plugin for Kimai 2 which checks if one of your users violated the German break time law + nominal and actual work time comparison + overtime view.

2020-09-18 12:01 UTC, hmr-it-jr commented
@kevinpapst now I'm done with adding commits 😄 

If I need to change something please write me

2020-09-18 12:03 UTC, kevinpapst commented
awesome 👍 will have a look later

2020-11-24 00:04 UTC, kevinpapst requested changes
Nice additions 👍 lets make the pages a bit more shiny 😄 and then it can be published

sorry for the long waiting time, I forgot about the PR

2020-11-24 00:04 UTC, kevinpapst commented on _store/hmr-it-controlling-bundle.md
> +- Handout for employees as pdf to see the worked hours of the month
pdf = PDF

2020-11-24 00:04 UTC, kevinpapst commented on _store/hmr-it-controlling-bundle.md
> +- Handout downloadable as a single pdf file for all employees or easy sendable via email to each employee (even to his private email account!)
pdf = PDF

2020-11-24 00:04 UTC, kevinpapst commented on _store/hmr-it-controlling-bundle.md
> +- See with one view in Billing/Export in Tabs how many invoices you have to create
Invoices for what?
Clarify where Kimai feature ends and your plugin starts

2020-11-24 00:04 UTC, kevinpapst commented on _store/hmr-it-hasworked-bundle.md
> +title: HasWorked Plugin
Plugin lowercase = plugin (to be consistent with all other store items)

2020-11-24 00:04 UTC, kevinpapst commented on _store/hmr-it-hasworked-bundle.md
> +name: HasWorked Plugin (notify users if they haven't entered times)
Plugin lowercase = plugin (to be consistent with all other store items)

2020-11-24 00:04 UTC, kevinpapst commented on _store/hmr-it-hasworked-bundle.md
> +intro: "A Kimai2 plugin to send emails not users that don't have any entries on the current day yet"
that sentence sounds strange (check not & yet)

2020-11-24 00:04 UTC, kevinpapst commented on _store/hmr-it-recordbook-bundle.md
> +title: RecordBook Plugin
Plugin lowercase = plugin (to be consistent with all other store items)

2020-11-24 00:04 UTC, kevinpapst commented on _store/hmr-it-recordbook-bundle.md
> +name: RecordBook Plugin (Berichtsheft für Azubis)
Plugin lowercase = plugin (to be consistent with all other store items)

2020-11-24 00:04 UTC, kevinpapst commented on _store/hmr-it-recordbook-bundle.md
> +        description: "Trainees see the weeks and can download the pdf"
pdf = PDF

2020-11-24 12:58 UTC, kevinpapst commented on _store/hmr-it-controlling-bundle.md
> +- Get notified if one of your user's birthday is coming soon
See Requires section, understand!

2020-11-24 12:59 UTC, kevinpapst approved these changes

2020-11-24 13:12 UTC, merged

2020-11-24 13:18 UTC, kevinpapst commented
Muchas gracias for extending the Kimai plugin family!